config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', as: :destroy_user_session
  end
  resource :user, only: [:edit, :update], controller: 'users'
  resources :blogs do
    resources :entries, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy] do
        member do
          put 'approve'
        end
      end
    end
  end
  root to: 'blogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :entries

  validates :title, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @q = Blog.ransack(params[:q])
    @blogs = @q.result.includes(:user)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @q = @blog.entries.ransack(params[:q])
    @entries = @q.result
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title)
    end

    def correct_user
      unless current_user?(@blog.user)
        flash[:warning] = I18n.t('flash.incorrect_user')
        redirect_to(root_path)
      end
    end

end

app/views/blogs/_form.html.haml
= simple_form_for blog, wrapper: :with_numbers do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  = f.input :title, number: 1
  = f.button :submit, class: "btn-primary"

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form', blog: @blog

.d-flex.flex-row.mt-2
  = link_to 'Show', @blog, class: "btn btn-link"
  = link_to 'Back', blogs_path, class: "btn btn-link"

app/views/blogs/index.html.haml
%h1
  Blogs
  - if user_signed_in?
    = link_to new_blog_path, class: "btn btn-sm btn-primary" do
      = icon('fas', 'plus')
      New Blog

= search_form_for @q, class: 'form-inline' do |f|
  = f.label :title_cont, class: 'my-1 mr-2'
  = f.search_field :title_cont, class: 'form-control mb-2 mr-sm-2'
  = f.label :user_name_cont, 'Author は以下を含む', class: 'my-1 mr-2'
  = f.search_field :user_name_cont, class: 'form-control mb-2 mr-sm-2'
  = f.submit class: 'btn btn-info mb-2 mr-sm-2'

%table.table
  %thead
    %tr
      %th{scope: "col"} Title
      %th{scope: "col"} Author
      %th{colspan: "3", scope: "col"}
        %tbody
          - @blogs.each do |blog|
            %tr{ id: "blog-row-#{blog.id}" }
              %td= blog.title
              %td= blog.user.name
              %td= link_to 'Show', blog
              - if user_signed_in? && current_user?(blog.user)
                %td= link_to 'Edit', edit_blog_path(blog)
                %td= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }
              - else
                %td
                %td

app/views/blogs/new.html.haml
%h1 New blog

= render 'form', blog: @blog

.d-flex.flex-row.mt-2
  = link_to 'Back', blogs_path, class: "btn btn-link"

app/views/blogs/show.html.haml
%h1
  = @blog.title
  - if user_signed_in? && current_user?(@blog.user)
    = link_to edit_blog_path(@blog), id: "blog-edit-link", class: "m-2 btn btn-sm btn-secondary" do
      = icon 'fas', 'edit'
      Edit

.d-flex.flex-row.mt-2
  = link_to 'Back', blogs_path, class: "btn btn-link"

.mt-2
  %h2.m-2.pt-2
    Entries
    - if user_signed_in? && current_user?(@blog.user)
      = link_to new_blog_entry_path(@blog), class: "btn btn-sm btn-primary" do
        = icon('fas', 'plus')
        New Entry

  = search_form_for @q, url: blog_path(@blog), class: 'form-inline' do |f|
    = f.label :title_cont, class: 'my-1 mr-2'
    = f.search_field :title_cont, class: 'form-control mb-2 mr-sm-2'
    = f.label :body_cont, class: 'my-1 mr-2'
    = f.search_field :body_cont, class: 'for-mcontrol mb-2 mr-sm-2'
    = f.submit

  %table.table
    %thead
      %tr
        %th{scope: "col"} Title
        %th Body
        %th{colspan: "3", scope: "col"}
    %tbody
      - @entries.each do |entry|
        %tr{ id: "entry-row-#{entry.id}" }
          %td= entry.title
          %td= entry.body
          %td= link_to 'Show', blog_entry_path(@blog, entry)
          - if user_signed_in? && current_user?(@blog.user)
            %td= link_to 'Edit', edit_blog_entry_path(@blog, entry)
            %td= link_to 'Destroy', blog_entry_path(@blog, entry), method: :delete, data: { confirm: 'Are you sure?' }
          - else
            %td
            %td