config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', as: :destroy_user_session
  end
  resource :user, only: [:edit, :update], controller: 'users'
  resources :blogs do
    resources :entries, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy] do
        member do
          put 'approve'
        end
      end
    end
  end
  root to: 'blogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :blog
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_blog
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :correct_user, only: [:new, :edit, :create, :update, :destroy]

  # GET /blogs/1/entries/1
  # GET /blogs/1/entries/1.json
  def show
    @new_comment = Comment.new
  end

  # GET /blogs/1/entries/new
  def new
    @entry = Entry.new
  end

  # GET /blogs/1/entries/1/edit
  def edit
  end

  # POST /blogs/1/entries
  # POST /blogs/1/entries.json
  def create
    @entry = Entry.new(entry_params)
    respond_to do |format|
      if @entry.save
        format.html { redirect_to [@blog, @entry], notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: [@blog, @entry] }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1/entries/1
  # PATCH/PUT /blogs/1/entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to [@blog, @entry], notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: [@blog, @entry] }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1/entries/1
  # DELETE /blogs/1/entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to @blog, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_blog
      @blog = Blog.find(params[:blog_id])
    end

    def set_entry
      @entry = Entry.find(params[:id])
      unless @entry.blog_id == @blog.id
        head :not_found
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body).merge(blog_id: params[:blog_id])
    end

    def correct_user
      unless current_user?(@blog.user)
        flash[:warning] = I18n.t('flash.incorrect_user')
        redirect_to(root_url)
      end
    end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.haml
= simple_form_for [blog, entry], wrapper: :with_numbers do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  = f.input :title, number: 1
  = f.input :body, number: 2
  = f.button :submit, class: "btn-primary"

app/views/entries/edit.html.haml
%h1 Editing Entry

= render 'form', blog: @blog, entry: @entry

.d-flex.flex-row.mt-2
  = link_to 'Show', blog_entry_path(@blog, @entry), class: "btn btn-link"
  = link_to 'Back', @blog, class: "btn btn-link"

app/views/entries/new.html.haml
%h1 New Entry

= render 'form', blog: @blog, entry: @entry

.d-flex.flex-row.mt-2
  = link_to 'Back', @blog, class: "btn btn-link"

app/views/entries/show.html.haml
%h1
  = @entry.title
  - if user_signed_in? && current_user?(@blog.user)
    = link_to edit_blog_entry_path(@blog, @entry), id: "entry-edit-link", class: "m-2 btn btn-sm btn-secondary" do
      = icon 'fas', 'edit'
      Edit

%p
  = @entry.body

.d-flex.flex-row.mt-2
  = link_to 'Back', @blog, class: "btn btn-link"

.mt-2
  %h3 Comments

  %table.table
    %tbody
      - @entry.comments.each do |comment|
        %tr{ id: "comment-row-#{comment.id}" }
          - if comment.status == "approved"
            %td= comment.body
            %td
          - else
            %td (承認待ち)
            - if user_signed_in? && current_user?(@blog.user)
              %td= link_to 'Approve', approve_blog_entry_comment_path(@blog, @entry, comment), method: :put
            - else
              %td
          - if user_signed_in? && current_user?(@blog.user)
            %td= link_to 'Destroy', blog_entry_comment_path(@blog, @entry, comment), method: :delete, data: { confirm: 'Are you sure?' }
          -else
            %td

  - if user_signed_in?
    .card
      .card-body
        %h4.card-title New comment
        = simple_form_for [@blog, @entry, @new_comment] do |f|
          = f.error_notification
          = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
          = f.input :body
          = f.button :submit, class: "btn-primary"